### ISSUE TITLE
`PrintfSigOverrider` should find variants of printf

### ISSUE THREAD

**Issue by JayFoxRox** [astrelsky/ghidra_scripts#2]
I think the script should be more aggressive in its approach.
The code for detecting a `printf` is here: https://github.com/astrelsky/ghidra_scripts/blob/1e7e1c3396ac03910e26cd132cec6d07f92b77ea/PrintfSigOverrider.java#L91-L101

However, I have a couple of functions which either fail the name test (`PRINT_F = "printf"` using case-sensitive search) or don't have the format string as parameter 0.

Prominent examples:
- `snprintf`
- `sprintf`

However, many more variations exist.

It might be worth experimenting with supporting all literal format specifier strings which are followed by a variadic arguments.

**Comment by astrelsky** [comment]
There is now an analyzer built in to Ghidra which will do this. This script will be removed at a later date.

**Comment by JayFoxRox** [comment]
> There is now an analyzer built in to Ghidra which will do this

This is new to me, which version added it, and where is the documentation for that feature?

**Comment by astrelsky** [comment]
> > There is now an analyzer built in to Ghidra which will do this
> 
> This is new to me, which version added it, and where is the documentation for that feature?

It is present in the Ghidra 10.0 Beta which is planned to be released as a final Ghidra 10.0 later this month.
