### ISSUE TITLE
How to select the correct label?

### ISSUE THREAD

**Issue by mediotex** [astrelsky/ghidra_scripts#3]
ResolveFidScript.java, the script description says:
```
// Displays a table of known FID_conflicts containing an action that allows the user
// to select the correct label. After the label has been selected all remaining FID_conflict
// labels are removed from the address and the selected label is demangled and re-applied
// if necessary.

```

I have a large amount of `FID_conflict:_GLOBAL__` functions: its not clear, how to select the correct label?

ghidra 11.1.1 on Linux

![FID2](https://github.com/user-attachments/assets/acd9cefb-f0b8-41b6-929e-c3aa696b960f)

**Comment by astrelsky** [comment]
To select the correct label, go through all 810+ conflicts and determine which one is correct. When you have found the correct one, name it "strtok" and delete the other labels.
